### ISSUE TITLE
`schedule_current.start` provides an inaccurate time.

### ISSUE THREAD

**Issue by coldshouldermedia** [williamjacksn/python-rainwave-client#240]
`schedule_current.start` provides an inaccurate time, ~2 days in the future.

When run at ~ `2024-08-18 16:42` local, `schedule_current.start` provides `2024-08-20 14:37:45`

**Comment by williamjacksn** [comment]
Fixed in https://github.com/williamjacksn/python-rainwave-client/commit/f505083bb833cbe267dc60c94af220086ba125ff and will be included in the next release.

**Comment by williamjacksn** [comment]
I just released version 2024.2: https://github.com/williamjacksn/python-rainwave-client/releases/tag/2024.2

`schedule_current.start` will continue to be inaccurate, because it matches the direct API response, but you can now use `schedule_current.start_actual` directly.
